name: calendar_view
description: A Flutter package allows you to easily implement all calendar UI and calendar event functionality.
version: 1.0.6
homepage: https://github.com/AfriDoctor/flutter_calendar_view
publish_to: 'https://dart.cloudsmith.io/afridoctor/flutter_calendar_view'

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  timezone: ^0.9.2

dev_dependencies:
  dcli: ^3.3.2
  flutter_test:
    sdk: flutter
  http: ^1.2.0
  process_run: ^0.14.1+3
  yaml: ^3.1.2
  yaml_writer: ^2.0.0

flutter:
